plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  "tag:env": dev
compose:
  ansible_host: instance_id
keyed_groups:
  - key: tags.env
    prefix: env_
hostnames:
  - instance-id
aws_profile: pro
