pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    timestamps()
  }

  stages {
    stage('Checkout Packer Code') {
      steps {
        checkout scm
      }
    }

    stage('Build AMI') {
      steps {
        dir('packer') {
          sh 'packer init ubuntu-golden-ami.pkr.hcl'
          sh './script/build_golden-ami.sh'
          archiveArtifacts artifacts: 'manifest.json', fingerprint: true
        }
      }
    }

    stage('Store AMI ID') {
      steps {
        script {
          // Extract AMI ID from Packer manifest
          def manifest = readJSON file: 'manifest.json'
          def amiId = manifest.builds[-1].artifact_id.split(':')[-1]
          
          // Store AMI ID in SSM Parameter Store for Terraform
          sh """
          aws ssm put-parameter \
            --name "/myapp/dev/ami-id" \
            --value ${amiId} \
            --type String \
            --overwrite
          """
          
          echo "AMI stored in SSM Parameter Store: ${amiId}"
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
